In [36]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [37]:
df4 = pd.DataFrame({
    'Roll' : [2203098 , 2203122 , 2203132],
    'Name' : ['sifat','sejuti','lamia'],
    'CGPA' : [3.44,3.76,3.86]
})

In [38]:
df2 = pd.DataFrame([[2203098,2203122,2203132],["sifat","sejuti","lamia"],
                   [3.44,3.76,3.86]], columns = ['Roll','Name','CGPA'])

In [39]:
arr = np.array([[1, 2], [3, 4]])
df3 = pd.DataFrame(arr, columns=['A', 'B'])

In [48]:
df = pd.read_csv('Iris.csv',index_col= 0)
df.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [41]:
df.shape
df.info()
df.describe()
df.describe(include = 'all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-setosa
freq,NaN,NaN,NaN,NaN,NaN,50
mean,75.500000,5.843333,3.054000,3.758667,1.198667,NaN
std,43.445368,0.828066,0.433594,1.764420,0.763161,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,38.250000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.500000,5.800000,3.000000,4.350000,1.300000,NaN
75%,112.750000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [52]:
df.dtypes
df.columns
df.index
df.tail(5)
df.sample(5)
df.memory_usage() #memory usage per column

Index            1200
SepalLengthCm    1200
SepalWidthCm     1200
PetalLengthCm    1200
PetalWidthCm     1200
Species          1200
dtype: int64

3.Selection and Indexing

In [46]:
df['Id']
df[['Id','SepalLengthCm']]

      Id  SepalLengthCm
0      1            5.1
1      2            4.9
2      3            4.7
3      4            4.6
4      5            5.0
..   ...            ...
145  146            6.7
146  147            6.3
147  148            6.5
148  149            6.2
149  150            5.9

[150 rows x 2 columns]

In [67]:
df.iloc[0]

SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 1, dtype: object

In [61]:
df.iloc[:,0:3]

     SepalLengthCm  SepalWidthCm  PetalLengthCm
Id
1              5.1           3.5            1.4
2              4.9           3.0            1.4
3              4.7           3.2            1.3
4              4.6           3.1            1.5
5              5.0           3.6            1.4
..             ...           ...            ...
146            6.7           3.0            5.2
147            6.3           2.5            5.0
148            6.5           3.0            5.2
149            6.2           3.4            5.4
150            5.9           3.0            5.1

[150 rows x 3 columns]

In [63]:
df.iloc[0:3,0:2]

    SepalLengthCm  SepalWidthCm
Id
1             5.1           3.5
2             4.9           3.0
3             4.7           3.2

In [64]:
df.loc[1]

SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 1, dtype: object

In [72]:
df[df['SepalLengthCm'].isin([1,2,4,5])]

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id
5             5.0           3.6            1.4           0.2      Iris-setosa
8             5.0           3.4            1.5           0.2      Iris-setosa
26            5.0           3.0            1.6           0.2      Iris-setosa
27            5.0           3.4            1.6           0.4      Iris-setosa
36            5.0           3.2            1.2           0.2      Iris-setosa
41            5.0           3.5            1.3           0.3      Iris-setosa
44            5.0           3.5            1.6           0.6      Iris-setosa
50            5.0           3.3            1.4           0.2      Iris-setosa
61            5.0           2.0            3.5           1.0  Iris-versicolor
94            5.0           2.3            3.3           1.0  Iris-versicolor